#this is the name of the workflow that will be displayed in the actions tab
name: CICD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: This is the environment value where the workflow runs
        required: true
        type: choice
        default: dev
        options:
          - dev
          - prod
          - staging
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "Code clone from GitHub."
  build:
     needs: code
     runs-on: ubuntu-latest
     steps:
       - name: build the code
         run: echo "Docker Build in progress."
  test:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: test the code
          run: echo "Docker test in progress."
  deploy:
      needs: [test, build]
      runs-on: ubuntu-latest
      steps:
        - name: deploy the code
          run: echo "Docker run in progress."
