name: self-hosted-runner

on: workflow_dispatch

jobs:

  greet:
    runs-on: self-hosted
    steps:
      - name: Say hello to the user
        run: |
          echo "Hello $whoami"

  new-file:
    runs-on: self-hosted
    steps:
      - name: Create a new file
        run: |
          echo "This file is created by Self Hosted Runner, which is visble in your EC2 instance" > runner.txt
    needs: greet

  list-file:
    runs-on: self-hosted
    steps:
      - name: Verify the file is created
        run: |
          ls -l runner.txt
    needs: new-file
