name: Installing nginx and run the page

on:
  workflow_dispatch: 

jobs:
  installing-tool:
    runs-on: ubuntu-latest
    steps:
      - name: install the nginx
        run: |
          sudo apt update
          sudo apt install nginx -y
          sudo systemctl start nginx
      
        
      
      
